root: ./docs/
ignore: 
  - ./scripts/
  
redirects:
  overview-liquid-markets: archive/overview-liquid-markets.md
  video-tutorial-how-to-use-portal: archive/video-tutorial-how-to-use-portal.md
  video-tutorial-how-to-manually-add-tokens-to-your-wallet: archive/video-tutorial-how-to-manually-add-tokens-to-your-wallet.md
  tutorial-recovery-workflow: archive/tutorial-recovery-workflow.md

#* [Tutorial: NFT Portal](tutorial-nft-bridge.md)
#* [Tutorial: NFT Origin tool](tutorial-nft-origin-tool.md)
#* [Tutorial: How to send USDC from Solana to Ethereum](tutorial-how-to-send-usdc-from-solana-to-ethereum.md)
#* [Tutorial: How to send USDC from Ethereum to Solana](tutorial-how-to-send-usdc-from-ethereum-to-solana.md)
#* [Video Tutorial: How to use the Token Origin Verifier](video-tutorial-how-to-use-the-token-origin-verifier.md)
#* [Token Register](token-register/README.md)
#  * [Tutorial: Token registration](token-register/tutorial-token-register.md)